### ISSUE TITLE
The installation instructions result in python3.12 and things don't work

### ISSUE THREAD

**Issue by dstndstn** [KiDS-WL/kcap#26]
Hi,

I tried following the install instructions helpfully included in your top-level README.md.
Currently, anaconda3 will install python 3.12.3, and it seems like some of the code is not happy with some of the changes in python3.12 ...

```
(kcap_env) dlang@mn003:~/kcap$ cosmosis runs/config/KV450_no_sys.ini
Traceback (most recent call last):
  File "/home/dlang/.conda/envs/kcap_env/bin/cosmosis", line 2, in <module>
    import cosmosis_main
  File "/home/dlang/.conda/envs/kcap_env/bin/cosmosis_main.py", line 5, in <module>
    from future import standard_library
  File "/home/dlang/.conda/envs/kcap_env/lib/python3.12/site-packages/future/standard_library/__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

I understand that's not a problem in the `kcap` code itself, but it seems like maybe the `future` package is not as future proof as one might hope...

Maybe you want to pin the python version in the `conda_env.yaml` file?

**Comment by cheymans** [comment]
Hi @dstndstn 
Thanks for the feedback.  As part of the DES+KiDS joint cosmic shear analysis project we integrated most of KCAP into CosmoSIS and the CosmoSIS standard library (v3.3 onwards). 
 
https://github.com/joezuntz/cosmosis-standard-library/blob/main/examples/des-y3_and_kids-1000.ini

If it was COSEBIs or 2pt I+/- you’re interested in, then I’d recommend just following this above ini file.  If it’s bandpass power spectra, then maybe your message will give us the necessary push to also port that over to the official CosmoSIS repo so we can formally close this one.

**Comment by dstndstn** [comment]
Hi Catherine,  Nice to hear from you!  I'm investigating this for a colleague so will get them to chime in here.
Thanks!
-dustin

**Comment by tilmantroester** [comment]
Hi Dustin - this repository exists mainly for legacy reasons and I'd recommend not using it for any analysis at this point. In addition to Catherine's pointer to the what's in the CSL, I have a working (but not super well-tested) pure-python implementation of all the statistics that I should put somewhere. This does away with the need to compile anything and the associated issues that tend to crop up.
